# Generated by Django 5.1.1 on 2024-09-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostCaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
                ('twitch', models.URLField(max_length=80)),
                ('twitter', models.URLField(max_length=80)),
                ('instagram', models.URLField(max_length=80)),
                ('reel', models.URLField(max_length=80)),
                ('dossier', models.URLField(max_length=80)),
                ('photo', models.ImageField(upload_to='HostCasters_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
                ('twitch', models.URLField(max_length=80)),
                ('youtube', models.URLField(max_length=80)),
                ('twitter', models.URLField(max_length=80)),
                ('instagram', models.URLField(max_length=80)),
                ('tiktok', models.URLField(max_length=80)),
                ('photo', models.ImageField(upload_to='influencers_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
                ('twitch', models.URLField(max_length=80)),
                ('youtube', models.URLField(max_length=80)),
                ('twitter', models.URLField(max_length=80)),
                ('instagram', models.URLField(max_length=80)),
                ('game', models.CharField(max_length=40)),
                ('role', models.CharField(max_length=40)),
                ('former', models.TextField(max_length=100)),
                ('photo', models.ImageField(upload_to='players_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
                ('twitch', models.URLField(max_length=80)),
                ('youtube', models.URLField(max_length=80)),
                ('twitter', models.URLField(max_length=80)),
                ('instagram', models.URLField(max_length=80)),
                ('tiktok', models.URLField(max_length=80)),
                ('photo', models.ImageField(upload_to='streamers_photos/')),
            ],
        ),
    ]
